# Generated by Django 3.1.8 on 2021-11-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('quantity', models.CharField(max_length=99)),
                ('details', models.TextField()),
            ],
        ),
    ]
