# Generated by Django 3.1.8 on 2021-11-01 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='front_order',
        ),
    ]
