# Generated by Django 3.1.8 on 2021-11-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211101_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='back_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('quantity', models.CharField(max_length=99)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fullstack_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('quantity', models.CharField(max_length=99)),
                ('details', models.TextField()),
            ],
        ),
    ]
