# Generated by Django 3.1.8 on 2021-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_back_order_fullstack_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_order',
            name='username',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
