# Generated by Django 3.1.8 on 2021-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_front_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='back_order',
            name='username',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='fullstack_order',
            name='username',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
