# Generated by Django 3.1.8 on 2021-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211102_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_order',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='front_order',
            name='status',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='fullstack_order',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fullstack_order',
            name='status',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
